### ISSUE TITLE
Exception on ChangeBlockEvent

### ISSUE THREAD

**Issue by LemADEC** [Erigitic/TotalEconomy#102]
As of
forge-1.10.2-12.18.1.2094-universal.jar
spongeforge-1.10.2-2092-5.0.0-BETA-1770.jar
TotalEconomy-v1.5.1.jar
we've had an exception on console, not sure how to reproduce it:
```
[20:01:19] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.5.1, description=All in one economy plugin for Minecraft/Sponge, source=/home/princess/./plugins/TotalEconomy-v1.5.1.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
>       at com.erigitic.jobs.TEJobs.onPlayerPlaceBlock(TEJobs.java:465) ~[TEJobs.class:?]
>       at org.spongepowered.common.event.listener.PlaceListener_TEJobs_onPlayerPlaceBlock49.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:353) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:336) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:366) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140) ~[SpongeImpl.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:538) ~[TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:458) ~[TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:80) ~[BlockTickPhaseState.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:80) [BlockTickPhaseState.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:67) [TickPhase.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:184) [CauseTracker.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:243) [TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:644) [ls.class:?]
>       at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by MarkL4YG** [comment]
Whats the (string) ID of the block?

**Comment by LemADEC** [comment]
Pretty sure vanilla block names have no "minecraft" prefixes in some cases

**Comment by Erigitic** [comment]
That may be the case, but it would be extremely helpful if we knew the exact block that was placed that caused the error to occur.

**Comment by LemADEC** [comment]
Could we detect the issue and post the block name in console for further investigation?

**Comment by MarkL4YG** [comment]
You can try [this](https://drive.google.com/file/d/0B-XTkzS0225PV2g5UlN1YjNiS2c/view?usp=sharing) release, it is built on [branch "issue/102" from "develop"].(https://github.com/MarkL4YG/TotalEconomy/tree/issue/102) of my fork and should log the block name right before the exception.

@Erigitic I didn't know if you mind me creating a draft-release for this purpose, so I just uploaded it to my drive.

**Comment by Erigitic** [comment]
@MarkL4YG Not at all. 

@LemADEC Go ahead and give the release a shot and get back to us with the block name.

**Comment by LemADEC** [comment]
There you go
```
[10:53:59] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.5.1, description=All in one economy plugin for Minecraft/Sponge, source=/home/prin
cess/./plugins/TotalEconomy-logs#102.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
>       at com.erigitic.jobs.TEJobs.onPlayerPlaceBlock(TEJobs.java:469) ~[TEJobs.class:?]
>       at org.spongepowered.common.event.listener.PlaceListener_TEJobs_onPlayerPlaceBlock51.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:353) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:336) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:366) ~[SpongeModEventManager.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140) ~[SpongeImpl.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:538) ~[TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:458) ~[TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$processPostTick$1(BlockTickPhaseState.java:80) ~[BlockTickPhaseState.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) [CapturedSupplier.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.processPostTick(BlockTickPhaseState.java:80) [BlockTickPhaseState.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.phase.tick.TickPhase.unwind(TickPhase.java:67) [TickPhase.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:184) [CauseTracker.class:1.10.2-2092-5.0.0-BETA-1770]
>       at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:243) [TrackingUtil.class:1.10.2-2092-5.0.0-BETA-1770]
>       at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:644) [ls.class:?]
>       at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
...
[11:00:56] [Server thread/INFO] [totaleconomy]: BlockPlaceEvent: Block ID is "windygarden"
[11:00:56] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.5.1, description=All in one economy plugin for Minecraft/Sponge, source=/home/princess/./plugins/TotalEconomy-logs#102.jar}
java.lang.ArrayIndexOutOfBoundsException
...
[11:22:27] [Server thread/INFO] [totaleconomy]: BlockPlaceEvent: Block ID is "frostgarden"
[11:22:27] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.5.1, description=All in one economy plugin for Minecraft/Sponge, source=/home/princess/./plugins/TotalEconomy-logs#102.jar}
java.lang.ArrayIndexOutOfBoundsException
```

This happens when placing Pam's Harvestcraft gardens. Breaking them doesn't cause the issue. Nobody was online at those time (just me AFK), so I guess it's world generation or some form of self propagation.
I can reproduce the first one by placing a garden manually.
The registry name seems correct through:
![image](https://cloud.githubusercontent.com/assets/4776032/19214624/84371630-8d88-11e6-9d68-afa600e1e007.png)

@MatrexsVigil any thought on this?

**Comment by MarkL4YG** [comment]
Just to mention it: I'm going to test some theories, we'll see if I come up with anything.

**Comment by MarkL4YG** [comment]
After debugging a little, the cause seems to be [this method](https://github.com/MatrexsVigil/harvestcraft/blob/1.9.4-1.10.2a/java/com/pam/harvestcraft/blocks/WindyGardenBlock.java#L24) which seems to override or replace the normal way Sponge returns the block name and only returns "windygarden".

I don't know Forge enough to tell if that method is supposed to be explicitly declared but since it's missing the ``@Override`` annotation and there's no such method in the Sponge/Forge or Minecraft interfaces for ``Block`` I would guess that @MatrexsVigil created it for mod-internal usage.

@MatrexsVigil If this method is really just used internally I would suggest changing the name to something more unique to avoid having such problems in the future.

@Erigitic As I mentioned: Changing to using the complete ID would resolve the issue as well

**Comment by Erigitic** [comment]
@MarkL4YG By complete id you mean using, for example, "minecraft:stone" versus just using "stone"?
