### ISSUE TITLE
Error on /sponge plugins reload

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#119]
```
[14:52:29] [Server thread/ERROR] [Sponge]: Could not pass GameReloadEvent$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.5.2, description=All in one economy plugin for Minecraft/Sponge, source=/home/frani/MagiBeta/mods/TotalEconomy-v1.5.2.jar}
java.lang.NullPointerException
        at com.erigitic.main.TotalEconomy.onGameReload(TotalEconomy.java:180) ~[TotalEconomy.class:?]
        at org.spongepowered.common.event.listener.GameReloadEventListener_TotalEconomy_onGameReload52.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.common.command.SpongeCommand.lambda$getPluginsCommand$8(SpongeCommand.java:471) ~[SpongeCommand.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) [ChildCommandElementExecutor.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) [CommandSpec.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) [SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2010]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-2010]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Erigitic** [comment]
Thanks for reporting this error. Do you happen to have Jobs disabled? It looks like I never added code to check if Jobs were disabled or not before I went about reloading the config.

**Comment by Eufranio** [comment]
Yes, I have

**Comment by Erigitic** [comment]
Alright, then this will be an easy fix that I'll get fixed up today. Thanks again!
