### ISSUE TITLE
Error on player login

### ISSUE THREAD

**Issue by Eufranio** [Erigitic/TotalEconomy#149]
When a player logs into the server, this error appears in the console:

```
[19:20:46] [Server thread/ERROR] [Sponge/]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.6.0-DEV, description=All in one economy plugin for Minecraft/Sponge, source=/home/container/mods/TotalEconomy-v1.6.0-DEV.jar}
java.lang.NullPointerException
	at com.erigitic.main.TotalEconomy.onPlayerJoin(TotalEconomy.java:184) ~[TotalEconomy.class:?]
	at org.spongepowered.common.event.listener.JoinListener_TotalEconomy_onPlayerJoin84.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2199]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2199]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2199]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2199]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2199]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2199]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1627) [mp.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
```

Using TotalEconomy-1.6.0-DEV

**Comment by EmanYm** [comment]
Although I'm sure Erigitic likes to know there's an issue, it's never suggested to use DEV builds on a production/live server
[version 1.5.3](https://github.com/Erigitic/TotalEconomy/releases/tag/v1.5.3) was build on the same SpongeAPI and Forge version as TotalEconomy1.6.0

**Comment by MarkL4YG** [comment]
Yeah, I would suggest using a release version until we can investigate this further.
If you could provide further information like the sponge version it'll help us track down the issue.

Stack trace points [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/main/TotalEconomy.java#L184) which shows that the code on GitHub doesn't match the originally compiled source (as comments aren't executable lines).
But as I don't think the accountManager is null at this point it might have something to do with Sponge - Further speculation when we know the Sponge version that's been used by  @Eufranio

**Comment by Eufranio** [comment]
I'm running SpongeForge,
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-982a6b0
    SpongeForge: 1.10.2-2221-5.2.0-

**Comment by MarkL4YG** [comment]
@Eufranio can you supply the SF build version?
Format should be ``1.10.2-2221-5.2.0-BETA-<build>`` as you can see [here](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2).

**Comment by Eufranio** [comment]
Yeah, that's what I posted.
`SpongeForge-1.10.2-2221-5.2.0-BETA-2202`

**Comment by MarkL4YG** [comment]
@Eufranio look again ;) you're missing the build in the first post ^^

**Comment by EmanYm** [comment]
>SpongeForge: 1.10.2-2221-5.2.0-BETA-2202
Minecraft Forge: 12.18.3.2185

You're using Forge 2185, but the version of the sponge you're using is 2221.
[Update your forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) to at least 2221.
>The format of the filename is spongeforge-{MCVersion}-{ForgeVersion}-{SpongeAPIVersion}-{SpongeBuildId}

You might also need to downgrade your SpongeForge to [API 5.1.0. BETA 2193.](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2)  You're using 5.2.0
API versions are intentionally not backward compatible.  I had [asked this awhile ago](https://forums.spongepowered.org/t/will-api5-plugins-function-in-api6-environment/17488) for my own reasons.

**Comment by MarkL4YG** [comment]
@EmanYm 
> I think you might also need to downgrade your SpongeForge to API 5.1.0. BETA 2193. You're using 5.2.0
API versions are intentionally not backward compatible. I had asked this awhile ago for my own reasons.

Sorry to correct you but that's not actually correct.
The SpongeAPI major version is supposed to indicate incompatibility meaning that API6 isn't compatible to 2, 4, 5 or any other.  
 Minor version differences like 5.2.X and 5.1.X can become incompatible due to a few implementations changes but are supposed to be compatible when the plugin is carefully developed (you should for example always check ``Optional::isPresent`` if Sponge returns one as it may be present under the same circumstances in one build but not another)

Your thread is actually about just that: API 6 is __not__ backward compatible to API 6

**Comment by EmanYm** [comment]
Perhaps I misunderstood what Aaron typed.  Regardless, it's off topic.

Perhaps SpongeForge 5.2.0 will work as long as it's built on the same version of Forge as what you're using.

**Comment by MarkL4YG** [comment]
@EmanYm  I've already reproduced the issue on the right corresponding forge version - working on debugging now.

**Comment by EmanYm** [comment]
@MarkL4YG I will leave it to your capable hands, then. :P

**Comment by Eufranio** [comment]
Yeah, was going to say that, updating forge will not fix the issue.

**Comment by MarkL4YG** [comment]
Turns out: I'll have to delay any results for a few hours... the stable-5 branch of SpongeForge - which is the branch corresponding to the used SF version - refuses to compile/run - as nearly always...
Anyways. I'll come back when I've something to report.

**Comment by MarkL4YG** [comment]
I ended up consulting the Sponge IRC regarding my build issues.
This means it may take a while until I can come up with something as I need to fix those first...

Maybe @Erigitic can reproduce the issue within his development environment without having to change around Sponge versions and fix it from there.

**Comment by Erigitic** [comment]
I have not been able to reproduce the issue on my end, but I am using an older build of Sponge API/Forge, so this could very well be the reason why. I will update everything on my end tomorrow, test it out, and get back to you on this.

**Comment by MarkL4YG** [comment]
@Erigitic make sure to have a backup of your workspace... mine is completely useless now ( ``)

**Comment by MarkL4YG** [comment]
So, I'm back with results ^^

1. FYI: My issue with SF turns out to be a bug with the IDEA 2017.1 EAP that I was using due to another bug with breadcrumbs in 2016.* - I'll have to live with the last until both are resolved.

2. The error you're having has to do with the ``accountManager`` being ``null`` due to the Initialization event failing because [this](https://github.com/Erigitic/TotalEconomy/blob/feature-sql/src/main/java/com/erigitic/main/TotalEconomy.java#L132) line is outside the if-statement in the development version.
The SQLHandler construction failes due to missing login parameters - which aren't existing if you don't want to use sql. 

 @Eufranio since this issue is already resolved in the feature-sql branch my advice is just to use the stable releases for now.

@Erigitic I couldn't help but notice that this means you've created the development release on the ``develop`` branch but compiled the plugin on the ``feature-sql`` branch. ^^

**Comment by Eufranio** [comment]
Nice!

**Comment by Erigitic** [comment]
@MarkL4YG The **feature-sql** branch has not been merged into develop yet as there is a lot of code in there that breaks the plugin. I will go and add that fix to the develop branch though just so we can avoid this issue popping up again. Thanks.

**Comment by Erigitic** [comment]
@Eufranio I went and updated the dev release. Would you mind testing it out and seeing if the error still persists? Thanks.

**Comment by MarkL4YG** [comment]
Confirmed fixed on my end 👍
