### ISSUE TITLE
MySQL error?

### ISSUE THREAD

**Issue by Tenelia** [Erigitic/TotalEconomy#167]
Not very sure what happened here. MySQL worked fine for everything else. I tried using "Localhost" or even "127.0.0.0", but neither worked. Username and passwords looked correct.

`[Server thread/ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.6.0-DEV, description=All in one economy plugin for Minecraft/Sponge, source=mods\TotalEconomy-v1.6.0-DEV.jar}
java.lang.NullPointerException
	at com.erigitic.sql.SQLHandler.createDatabase(SQLHandler.java:75) ~[SQLHandler.class:?]
	at com.erigitic.config.AccountManager.setupDatabase(AccountManager.java:96) ~[AccountManager.class:?]
	at com.erigitic.config.AccountManager.<init>(AccountManager.java:71) ~[AccountManager.class:?]
	at com.erigitic.main.TotalEconomy.preInit(TotalEconomy.java:139) ~[TotalEconomy.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_TotalEconomy_preInit42.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-6.0.0-BETA-234]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) [SpongeEventManager.class:1.11.2-6.0.0-BETA-234]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) [SpongeEventManager.class:1.11.2-6.0.0-BETA-234]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:324) [SpongeEventManager.class:1.11.2-6.0.0-BETA-234]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:201) [SpongeImpl.class:1.11.2-6.0.0-BETA-234]
	at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:115) [SpongeVanilla.class:1.11.2-6.0.0-BETA-234]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$znp000(SourceFile:1223) [lh.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:112) [lh.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:436) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[22:48:50] [Server thread/INFO] [HikariDataSource]: HikariPool-2 - Started.`

**Comment by MarkL4YG** [comment]
Can you tell us if [this](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/sql/SQLHandler.java#L50) or the next error messages show up in the log?

**Comment by Erigitic** [comment]
Does your database url look something like this: `url="jdbc:mysql:[URL]:[PORT]"`?

**Comment by Tenelia** [comment]
I've currently entered it as `url="jdbc:mysql:localhost:3306"`

**Comment by MarkL4YG** [comment]
@Tenelia According to the exception the accountManager is null at [this](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/commands/PayCommand.java#L65) point. Can you look for any other exceptions?
There could also be a warning about TotalEconomy failing to connect to the database which is why @Erigitic asked you about your URL and if it's correct. You may check for such a line too.

@Erigitic Just by the way: I would include the exceptions in logger warnings like this so ppl who aren't familiar with finding errors can discover the problem more quickly.
[Here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/sql/SQLHandler.java#L52) for example can ``e`` just be included within the warning like this: ``logger.warn("stuff", e);`` which should print some part of the exception to the log.

**Comment by Tenelia** [comment]
@Erigitic I've currently entered it as url="jdbc:mysql:localhost:3306"

@MarkL4YG What's weird is that other plugins work using that exact URL line. The accounts and passwords all work too. It's just totaleconomy that's kicking up errors.

**Comment by MarkL4YG** [comment]
@Tenelia Glad you've found the source 👍 
SQL support currently belongs to the development releases. It will be documented once it's part of a stable release.

**Comment by Tenelia** [comment]
Alright. I hope all goes well on your release horizon! :)

**Comment by MarkL4YG** [comment]
- Closable - 
@Erigitic 
@Tenelia

**Comment by Erigitic** [comment]
Glad you got this fixed. I'll go ahead and update the url in the documentation.
