### ISSUE TITLE
user mysql error

### ISSUE THREAD

**Issue by cailibiao** [Erigitic/TotalEconomy#176]
Only change the：
-------------

```
database {
    enable=true
    password="123456"
    url="jdbc:mysql://localhost:3306/minecraft"
    user="root"
}
```
--------------
```
[STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]: java.sql.SQLSyntaxErrorException: Error preparing query: Unknown column 'dollar_balance' in 'field list'
If column exists but type cannot be identified (example 'select ? `field1` from dual'). Use CAST function to solve this problem (example 'select CAST(? as integer) `field1` from dual')
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:226)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:376)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:323)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQuery(MariaDbServerPreparedStatement.java:304)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.executeQuery(SQLQuery.java:61)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.<init>(SQLQuery.java:50)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.<init>(SQLQuery.java:35)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery$Builder.build(SQLQuery.java:324)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:142)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.commands.BalanceCommand.execute(BalanceCommand.java:58)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.lang.Thread.run(Thread.java:745)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Error preparing query: Unknown column 'dollar_balance' in 'field list'
If column exists but type cannot be identified (example 'select ? `field1` from dual'). Use CAST function to solve this problem (example 'select CAST(? as integer) `field1` from dual')
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.internal.packet.ComStmtPrepare.read(ComStmtPrepare.java:104)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prepareAndExecute(AbstractQueryProtocol.java:510)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:365)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    ... 33 more
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]: java.sql.SQLSyntaxErrorException: Error preparing query: Unknown column 'dollar_balance' in 'field list'
If column exists but type cannot be identified (example 'select ? `field1` from dual'). Use CAST function to solve this problem (example 'select CAST(? as integer) `field1` from dual')
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:226)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:376)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:323)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQuery(MariaDbServerPreparedStatement.java:304)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.executeQuery(SQLQuery.java:61)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.<init>(SQLQuery.java:50)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery.<init>(SQLQuery.java:35)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.sql.SQLQuery$Builder.build(SQLQuery.java:324)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.config.TEAccount.hasBalance(TEAccount.java:93)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.config.TEAccount.getBalance(TEAccount.java:103)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.api.service.economy.account.Account.getBalance(Account.java:143)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at com.erigitic.commands.BalanceCommand.execute(BalanceCommand.java:60)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[01:27:52] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SQLQuery:executeQuery:68]:  at java.lang.Thread.run(Thread.java:745)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Error preparing query: Unknown column 'dollar_balance' in 'field list'
If column exists but type cannot be identified (example 'select ? `field1` from dual'). Use CAST function to solve this problem (example 'select CAST(? as integer) `field1` from dual')
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.internal.packet.ComStmtPrepare.read(ComStmtPrepare.java:104)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prepareAndExecute(AbstractQueryProtocol.java:510)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:365)
[01:27:52] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    ... 35 more
[01:27:52] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'bal' for source EntityPlayerMP['Blue_Gardenia'/2942, l='world', x=182.50, y=73.00, z=242.50]: null
java.lang.NullPointerException
        at com.erigitic.sql.SQLQuery.recordExists(SQLQuery.java:95) ~[SQLQuery.class:?]
        at com.erigitic.config.TEAccount.hasBalance(TEAccount.java:95) ~[TEAccount.class:?]
        at com.erigitic.config.TEAccount.getBalance(TEAccount.java:103) ~[TEAccount.class:?]
        at org.spongepowered.api.service.economy.account.Account.getBalance(Account.java:143) ~[Account.class:1.10.2-2281-5.2.0-BETA-2350]
        at com.erigitic.commands.BalanceCommand.execute(BalanceCommand.java:60) ~[BalanceCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2281-5.2.0-BETA-2350]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2350]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2350]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2350]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2350]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2350]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2350]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by MarkL4YG** [comment]
Hey there, first let me address some formatting stuff: Please paste logs using quotes or better hastebin/pastebin so they're easier to read. Also use code blocks for snippets from your config so they're formatted properly.

---
Now your issue: Try using  
``url="jdbc:mysql://localhost:3306/`` instead of  
``url="jdbc:mysql://localhost:3306/minecraft"``  
TotalEconomy automatically selects a database named "totaleconomy" thus the db-name in the URL is redundand. This also causes your exception since TE seems to have failed creating the db. Probably due to lack of permission.  
To resolve this, create a database named "totaleconomy" and grant "ALL" on that database to the user you provide to TE.

**Comment by Erigitic** [comment]
@cailibiao Were you able to resolve this issue?

**Comment by MarkL4YG** [comment]
I guess no answer means "yes" ¯\_(ツ)_/¯

**Comment by Erigitic** [comment]
It sat for so long without a response that I'm assuming it was resolved. If not, hopefully @cailibiao will post a reply so we can reopen and get it fixed.

**Comment by YumaYamamoto** [comment]
@MarkL4YG I have that problem too... how to fix?

**Comment by MarkL4YG** [comment]
Try remaking you database and let TE re-create the tables.
