### ISSUE TITLE
No Automatic Payments Occur 

### ISSUE THREAD

**Issue by SjsolisZXA** [Erigitic/TotalEconomy#210]
Hello, Players who have taken on jobs are not being compensated for their work e.g a Miner won't gain any exp or dollars for mining ore items. 

**SpongeForge Version:** 1.10.2-2477-5.2.0-BETA-2637
**TotalEconomy Version:** TotalEconomy-1.6.0

**Comment by MarkL4YG** [comment]
Please attach a gist with your configuration files and a full server log for us to look into.

**Comment by MarkL4YG** [comment]
Oh and also: You may test if the development release works better for you as I would say it's about to become stable.

**Comment by MarkL4YG** [comment]
Update TotalEconomy [latest release is 1.7.0](https://github.com/Erigitic/TotalEconomy/releases)

**Comment by SjsolisZXA** [comment]
Is it compatible with the 5.2 API?

**Comment by MarkL4YG** [comment]
It is literally named "(API 5.2.0 / Minecraft 1.10.2)" :see_no_evil:

**Comment by SjsolisZXA** [comment]
Thanks. On the Ore page it's labeled for 1.11.2, that's why I was asking. I seem to be having thes issue on startup, though.
```
[07:20:05] [Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=totaleconomy, name=Total Economy, version=1.7.0, description=All in one economy plugin for Minecraft/Sponge, source=C:\Users\Salva\Desktop\Sponge 1.10.2\mods\TotalEconomy-1.7.0-LEGACY.jar}
java.lang.NullPointerException: content
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
        at org.spongepowered.api.text.Text.of(Text.java:813) ~[Text.class:1.10.2-2477-5.2.0-BETA-2637]
        at com.erigitic.main.TotalEconomy.lambda$preInit$0(TotalEconomy.java:137) ~[TotalEconomy.class:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_144]
        at com.erigitic.main.TotalEconomy.preInit(TotalEconomy.java:125) ~[TotalEconomy.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_TotalEconomy_preInit55.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234) [SpongeMod.class:1.10.2-2477-5.2.0-BETA-2637]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

```
[07:20:10] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=totaleconomy, name=Total Economy, version=1.7.0, description=All in one economy plugin for Minecraft/Sponge, source=C:\Users\Salva\Desktop\Sponge 1.10.2\mods\TotalEconomy-1.7.0-LEGACY.jar}
java.lang.NullPointerException: listener
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
        at org.spongepowered.common.event.SpongeEventManager.registerListener(SpongeEventManager.java:186) ~[SpongeEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.common.event.SpongeEventManager.registerListeners(SpongeEventManager.java:242) ~[SpongeEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at com.erigitic.main.TotalEconomy.init(TotalEconomy.java:197) ~[TotalEconomy.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_TotalEconomy_init51.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2477-5.2.0-BETA-2637]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234) [SpongeMod.class:1.10.2-2477-5.2.0-BETA-2637]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by MarkL4YG** [comment]
Do you happen to have SQL enabled? There's currently an unresolved issue with error reporting whenever SQL is not set up properly.

**Comment by SjsolisZXA** [comment]
No, it's set to false.

**Comment by Erigitic** [comment]
Try remaking the main configuration file (Delete totaleconomy.conf then rerun the server). From the looks of it, you have a 1.6.0 configuration file instead of a 1.7.0 one. The main configuration file was changed between these two releases.
