### ISSUE TITLE
1.12.2 repeating job scheduling exception?

### ISSUE THREAD

**Issue by smmmadden** [Erigitic/TotalEconomy#228]
Minecraft: 1.12.2
SpongeAPI Version: 7.0.0-SNAPSHOT-0ede943
Sponge Forge Version: 1.12.2-2529-7.0.0-BETA-2755
Forge: 14.23.1.2555
Total Economy Version: 1.7.1
JVM: 1.8.0_152
Server: Windows 10 Pro
Permissions: LuckPerms Sponge 4.0.62

I log into the server and within the first 30 seconds, the below is thrown in the console.
[10:20:24] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task Pay Day owned by Plugin{id=totaleconomy, name=Total Economy, version=1.7.1, description=All in one economy plugin for Minecraft/Sponge, source=D:\MC_PokemonRevival\mods\TotalEconomy-1.7.1.jar}, but an error occured.
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
        at com.erigitic.jobs.JobManager.lambda$startSalaryTask$0(JobManager.java:158) ~[JobManager.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2529-7.0.0-BETA-2755]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_152]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2529-7.0.0-BETA-2755]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:269) [SpongeMod.class:1.12.2-2529-7.0.0-BETA-2755]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_37_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

**Comment by MarkL4YG** [comment]
This is definitively caused by using the wrong API-version of TE.

**Comment by smmmadden** [comment]
got latest API version from here https://ore.spongepowered.org/Erigitic/Total-Economy/versions and using the 1.7.1-API_7 version it no longer occurs.  Thanks!
