### ISSUE TITLE
Error: org/spongepowered/api/event/cause/NamedCause

### ISSUE THREAD

**Issue by DcNdrew** [Erigitic/TotalEconomy#239]
Is this because Total Economy is made for API 6.0?

Sponge Version:  spongeforge-1.12.2-2555-7.0.0-BETA-2800
Forge Version:  forge-1.12.2-14.23.1.2571
Total Economy Version:  TotalEconomy-1.8.0-dev.3

### Console errors
[21:01:39] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'totaleconomy:setbal DcNdrew 2000' for source EntityPlayerMP['DcNdrew'/664440, l='Overworld', x=217.52, y=69.00, z=-46.71]: org/spongepowered/api/event/cause/NamedCause
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
at com.erigitic.commands.SetBalanceCommand.getTransactionResult(SetBalanceCommand.java:117) ~[SetBalanceCommand.class:?]
at com.erigitic.commands.SetBalanceCommand.execute(SetBalanceCommand.java:79) ~[SetBalanceCommand.class:?]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:383) ~[CommandSpec.class:1.12.2-2555-7.0.0-BETA-2800]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2555-7.0.0-BETA-2800]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-2555-7.0.0-BETA-2800]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2800]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2800]
at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4007) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

**Comment by Erigitic** [comment]
> Is this because Total Economy is made for API 6.0?

Yes it is. 1.8.0-dev is compiled using API 6 so it will not work on API 7.

**Comment by DcNdrew** [comment]
Okay, so I must use 1.7. As I see there's an API 7 version.

**Comment by Erigitic** [comment]
Here is the latest API 7 release: https://ore.spongepowered.org/Erigitic/Total-Economy/versions/1.7.1-API_7.

**Comment by DcNdrew** [comment]
Thank you, I already downloaded it. :)
