### ISSUE TITLE
Command /adminpay doesn't work

### ISSUE THREAD

**Issue by Michael-Weis** [Erigitic/TotalEconomy#246]
Sponge Version:  spongeforge-1.12.2-2586-7.1.0-BETA-2865
Forge Version:  forge-1.12.2-14.23.1.2601-universal
Total Economy Version:  TotalEconomy-1.8.0-dev.5

### Description of issue
Command /adminpay doesn't work
### Console errors
[13:11:48] [Server thread/INFO] [nucleus]: Server ran the command: /adminpay ZuRGs 10
[13:11:48] [Server thread/INFO]: Error occurred while executing command: org/spongepowered/api/event/cause/NamedCause
[13:11:48] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'adminpay ZuRGs 10' for source DedicatedServer: org/spongepowered/api/event/cause/NamedCause
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
        at com.erigitic.commands.AdminPayCommand.getTransactionResult(AdminPayCommand.java:127) ~[AdminPayCommand.class:?]
        at com.erigitic.commands.AdminPayCommand.execute(AdminPayCommand.java:76) ~[AdminPayCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2586-7.1.0-BETA-2865]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2586-7.1.0-BETA-2865]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-2586-7.1.0-BETA-2865]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by MarkL4YG** [comment]
The development releases are built against SpongeAPI 6.
