### ISSUE TITLE
baltop missing SQL integration

### ISSUE THREAD

**Issue by demon57730** [Erigitic/TotalEconomy#251]
Sponge Version:  spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
Forge Version:  forge-1.12.2-14.23.2.2625-universal.jar
Total Economy Version:  TotalEconomy-1.8.0.jar

### Description of issue
when I type / baltop or balancetop nothing happens and in the console I have it

### Console errors
[Server thread/ERROR] [Sponge]: Error occurred while executing command 'baltop' for source DedicatedServer: null
java.lang.NullPointerException: null
at com.erigitic.commands.BalanceTopCommand.execute(BalanceTopCommand.java:71) ~[BalanceTopCommand.class:?]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by MarkL4YG** [comment]
Please do - as the last instruction says - create a gist with your configuration files and your full server log.
Remember to redact or replace login information though. (or just reproduce on a testing environment)

**Comment by demon57730** [comment]
totaleconomy.conf : https://gist.github.com/demon57730/53cb573ba496fc05e50c104f224ebf9e

log server : https://gist.github.com/demon57730/e947328cc85b3692ffc3a98317d7505d

**Comment by MarkL4YG** [comment]
Okay, please first note that - according to your ``totaleconomy.conf`` you're using the luckyperms database for TotalEconomy. I highly advice you against doing so. Please create a new one for TE.  

Second the issue you're facing is coming from [this line(https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/commands/BalanceTopCommand.java#L71). It seems you found another spot where sql integration is missing.  
I'm sure @Erigitic can quickly fix that and include that fix in the next minor release.

**Comment by demon57730** [comment]
the database is me who create them with this name these a database or all the plugin used so these not a special database luckyperm
