### ISSUE TITLE
Total Economy DB Connection

### ISSUE THREAD

**Issue by tmoflash** [Erigitic/TotalEconomy#279]
Sponge Version:  spongevanilla-1.12.2-7.1.0-BETA-59
Forge Version:  N/A
Total Economy Version:  TotalEconomy-1.8.1

### Description of issue
I need a little guidance connecting to the database. To give a little more information here is the background of the issue.

I am using a panel that runs inside of a docker. Now I have set up mariadb/mysql and bind-address: 0.0.0.0. I also set up a user to allow “%” access from any ip. I know my docker ip. Now I have other plugins that are connecting fine. I am running into issues with total economy. TE runs fine not connected to database but I would like to use it across bungee network.

database {
enable=true
password=“mypassword”
url=“mysql://[172.18.0.1]:[3306]/[totaleconomy]”
user=“minecraft”
}

Any suggestions on how to get this to work?
### Console errors
[17:19:43 ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.8.1, description=All in one economy plugin for Minecraft/Sponge, source=mods/TotalEconomy-1.8.1.jar}
### Steps to reproduce
I can remove db connection and TE loads fine. Cannot when trying to connect.
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

**Comment by tmoflash** [comment]
Yes I am using Pterodactyl - guess the ip gave it away..hehe

I removed the brackets but still getting error:

``[15:44:36 ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=totaleconomy, name=Total Economy, version=1.8.1, description=All in one economy plugin for Minecraft/Sponge, source=mods/TotalEconomy-1.8.1.jar}
java.lang.NullPointerException: null
at com.erigitic.main.TotalEconomy.loadCurrencies(TotalEconomy.java:374) ~[TotalEconomy.class:?]
at com.erigitic.main.TotalEconomy.preInit(TotalEconomy.java:156) ~[TotalEconomy.class:?]
at org.spongepowered.common.event.listener.GamePreInitializationEventListener_TotalEconomy_preInit42.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-59]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) [SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) [SpongeEventManager.class:1.12.2-7.1.0-BETA-59]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:223) [SpongeImpl.class:1.12.2-7.1.0-BETA-59]
at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-7.1.0-BETA-59]
at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:121) [SpongeVanilla.class:1.12.2-7.1.0-BETA-59]
at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$bab000(SourceFile:1234) [nz.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by tmoflash** [comment]
One question I have. I am using maria db and that is how I am connecting to the other plugin. Does it matter if I use mysql but use the user 

User                    Host               Password
minecraft               %                 *encryptedPassword

What I am saying is. I know I can "use mysql" but I want to make sure that the user minecraft which has the wild card has access to mysql/mariadb or should I create a separate user for each?

**Comment by MarkL4YG** [comment]
I don't see anything preventing you from doing that.

Would you mind creating a gist with you server logs and your main TE configuration (password redacted of course)?

**Comment by MarkL4YG** [comment]
And what gave it away was more the concept of a panel dockerizing the game servers as there's few competition to Pterodactyl out there using that concept.

**Comment by tmoflash** [comment]
I was out of town for a few days, I'll take a look and post shortly

**Comment by tmoflash** [comment]
I have been out working on other things. What logs do you need? I am still having same issue. 

enable=true
		password=somepass
		url=“mysql://172.18.0.1:3306/totaleconomy”
		user=“minecraft”

**Comment by tmoflash** [comment]
Here is the gist - https://gist.github.com/tmoflash/f56f62141d4bf3ca1785659b9245ccd2

**Comment by tmoflash** [comment]
Any insight on anything I can check?

**Comment by MarkL4YG** [comment]
Caught up on work for university. But be sure - I won't forget about the issue ^^`

**Comment by MarkL4YG** [comment]
You've got an issue with your configuration files.  
The ``NullPointerException`` raised in [this line](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/main/TotalEconomy.java#L374) will cause TotalEconomy to not initialize correctly.  

Correct the issue with the ``currency`` node and see if it works.  

At the moment TE isn't really that good at dealing with misconfiguration (especially syntax errors) to be honest but I'm sure this will improve in the future.

**Comment by Erigitic** [comment]
Is it safe to close this issue? I think a separate issue should be made regarding proper handling of config issues.

**Comment by wittyphantom333** [comment]
Yes. I was able to find out it was the driver it was using to connect to MySQL was old.

Think it was resolved.

Sent from my iPhone

On Dec 11, 2018, at 9:57 AM, Eric <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it safe to close this issue? I think a separate issue should be made regarding proper handling of config issues.

**Comment by TonyoBlaster** [comment]
Same here...

java.lang.NullPointerException: null
	at com.erigitic.main.TotalEconomy.loadCurrencies(TotalEconomy.java:374) ~[TotalEconomy.class:?]
	at com.erigitic.main.TotalEconomy.preInit(TotalEconomy.java:156) ~[TotalEconomy.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_TotalEconomy_preInit48.handle(Unknown Source) ~[?:?]

**Comment by MarkL4YG** [comment]
Please do not bump resolved issues. Rather check whether or not the solution applies to you issue and if it doesn't, you can always open a new issue and discuss your situation with us.
