### ISSUE TITLE
plz fix this bug

### ISSUE THREAD

**Issue by Arobcher** [Erigitic/TotalEconomy#295]
Sponge Version:  spongeforge-1.12.2-2611-7.1.0-BETA-3002
Forge Version:  forge-1.12.2-14.23.1.2555-universal
Total Economy Version:  TotalEconomy-1.8.1

### Description of issue
totaleconomy MySQL with PoreRT compatibility issues
### Console errors
`[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]: java.sql.SQLException: Operation not allowed after ResultSet closed
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.mysql.jdbc.ResultSetImpl.isBeforeFirst(ResultSetImpl.java:6135)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.zaxxer.hikari.pool.HikariProxyResultSet.isBeforeFirst(HikariProxyResultSet.java)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.erigitic.sql.SqlQuery.recordExists(SqlQuery.java:100)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.erigitic.config.AccountManager.hasAccount(AccountManager.java:278)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.erigitic.config.AccountManager.getOrCreateAccount(AccountManager.java:215)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at com.erigitic.commands.BalanceCommand.execute(BalanceCommand.java:64)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at java.util.concurrent.FutureTask.run(Unknown Source)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[01:14:44] [Server thread/INFO] [STDERR]: [com.erigitic.sql.SqlQuery:recordExists:104]:         at java.lang.Thread.run(Unknown Source)`

### Steps to reproduce
Put PoreRT and TotalEconomy in MODS folder and configure TotalEconomy as MySQL
###
https://gist.github.com/Arobcher/33a631746291ed918b10d7e5ee2855c5
PoreRT: https://github.com/MCHanxi/PoreRT

**Comment by Erigitic** [comment]
I know why this is happening. This will be fixed. Thanks for reporting.
