### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by winsrp** [Erigitic/TotalEconomy#51]
```
[18:34:55] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Place$Impl to Plugin{id=TotalEconomy, name=Total Economy, version=1.3.2}
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.erigitic.jobs.TEJobs.onPlayerPlaceBlock(TEJobs.java:411) ~[TEJobs.class:?]
        at org.spongepowered.common.event.listener.PlaceListener_TEJobs_onPlayerPlaceBlock23.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:225) [SpongeModEventManager.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:264) [SpongeModEventManager.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:250) [SpongeModEventManager.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:127) [SpongeImpl.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:688) [CauseTracker.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445) [CauseTracker.class:1.8.9-1763-3.1.0-BETA-1177]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:108) [PacketUtil.class:1.8.9-1763-3.1.0-BETA-1177]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) [fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by Erigitic** [comment]
This is because Total Economy is not updated to work with the version of Sponge you are currently using. I have decided to wait till Sponge is updated  to 1.9 before updating. Sorry.
